In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
firms_attribute_in = pd.read_csv('CRAB/Inputs/micro_variable_firms_in_26850')
firms_attribute_out = pd.read_csv('CRAB/Inputs/micro_variable_firms_out_26850')
#firms_initialization = pd.read_csv('CRAB/Inputs/firms_attributes2')

In [4]:
firms_attribute_in= firms_attribute_in.loc[firms_attribute_in['Type'] == 'Cap']
# selecmax steps
max_step = firms_attribute_in['Step'].max()
firms_attribute_in = firms_attribute_in.loc[firms_attribute_in['Step'] == max_step]
# sort by AgentID
len(firms_attribute_in.sort_values(by=['AgentID']))

49

In [5]:
firms_attribute_out= firms_attribute_out.loc[firms_attribute_out['Type'] == 'Cap']
# selecmax steps
max_step = firms_attribute_out['Step'].max()
firms_attribute_out = firms_attribute_out.loc[firms_attribute_out['Step'] == max_step]
# sort by AgentID
len(firms_attribute_out.sort_values(by=['AgentID']))

49

In [6]:
firms_attribute_in.head(2)

,Unnamed: 0,Step,AgentID,Type,Lifecycle,Net_worth,OMEGA,Capital_amount,Wage,Size,...,Productivity,Price,Inventories,Subsidiary,Market_share,Capital_info,Profits,OMEGA.1,t,Quantity_ordered
0,6279,21,2,Cap,22.0,75.0,0.0,60.0,1.021638,0.0,...,"[0.9368343467085251, 1.1211988475586492]",1.231496,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
1,6280,21,3,Cap,22.0,75.0,0.0,60.0,1.099252,0.0,...,"[1.020911113692764, 1.138482494520367]",0.998097,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0

In [7]:
firms_attribute_out.head(2)

,Unnamed: 0,Step,AgentID,Type,Lifecycle,Net_worth,OMEGA,Capital_amount,Wage,Size,...,Productivity,Price,Inventories,Subsidiary,Market_share,Capital_info,Profits,OMEGA.1,t,Quantity_ordered
6279,6279,21,2,Cap,43.0,75.0,0.0,2.0,1.021638,0.0,...,"[0.9368343467085251, 1.1211988475586492]",1.231496,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6280,6280,21,3,Cap,43.0,75.0,0.0,2.0,1.099252,0.0,...,"[1.020911113692764, 1.138482494520367]",0.998097,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0

In [65]:
firms_attribute_out.sort_values(by=['AgentID'])

,Unnamed: 0,Step,AgentID,Type,Lifecycle,Net_worth,OMEGA,Capital_amount,Wage,Size,...,Productivity,Price,Inventories,Subsidiary,Market_share,Capital_info,Profits,OMEGA.1,t,Quantity_ordered
6321,6321,21,2,Cap,22.0,75.0,0.0,60.0,0.881072,0.0,...,"[0.9865872547403844, 0.92518974448353]",1.204440,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6292,6292,21,3,Cap,22.0,75.0,0.0,60.0,0.914552,0.0,...,"[1.0080906382560892, 0.9519918545120641]",1.024664,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6282,6282,21,4,Cap,22.0,75.0,0.0,60.0,0.984726,0.0,...,"[0.9846428461964827, 0.9061795027010492]",0.897177,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6300,6300,21,5,Cap,22.0,75.0,0.0,60.0,1.252173,0.0,...,"[1.1032527831409218, 0.9935333410437479]",0.849106,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6317,6317,21,6,Cap,22.0,75.0,0.0,60.0,0.926114,0.0,...,"[0.9341300270310959, 1.0908927266775632]",0.784433,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6281,6281,21,7,Cap,22.0,75.0,0.0,60.0,1.011333,0.0,...,"[1.0156715200218347, 0.9396871727843968]",0.835841,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6326,6326,21,8,Cap,22.0,75.0,0.0,60.0,1.090740,0.0,...,"[0.8927034827280631, 1.1165140208093915]",0.825033,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6324,6324,21,9,Cap,22.0,75.0,0.0,60.0,0.936852,0.0,...,"[1.13171729602474, 0.9938929905230182]",1.106197,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6320,6320,21,10,Cap,22.0,75.0,0.0,60.0,0.982197,0.0,...,"[0.8468549330298544, 0.9884498643009594]",1.096602,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6286,6286,21,11,Cap,22.0,75.0,0.0,60.0,1.090526,0.0,...,"[0.9831396275017417, 0.914764214634391]",1.070919,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6304,6304,21,12,Cap,22.0,75.0,0.0,60.0,1.040871,0.0,...,"[0.9994811817941509, 1.0791592803833407]",1.079901,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6294,6294,21,13,Cap,22.0,75.0,0.0,60.0,0.920738,0.0,...,"[1.117846704614349, 1.028021672630585]",1.031010,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6280,6280,21,14,Cap,22.0,75.0,0.0,60.0,0.960462,0.0,...,"[1.0640069801829746, 0.9590406227795077]",1.069797,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6290,6290,21,15,Cap,22.0,75.0,0.0,60.0,0.844580,0.0,...,"[1.1349877989403008, 1.0706985000460358]",1.174145,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6311,6311,21,16,Cap,22.0,75.0,0.0,60.0,1.037469,0.0,...,"[0.9650225447164517, 1.0076872961210337]",0.942045,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6293,6293,21,17,Cap,22.0,75.0,0.0,60.0,0.960818,0.0,...,"[1.2650668616177327, 0.896068645258712]",1.115553,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6284,6284,21,18,Cap,22.0,75.0,0.0,60.0,1.086559,0.0,...,"[1.1942986851022424, 1.0100534292279038]",0.879354,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6287,6287,21,19,Cap,22.0,75.0,0.0,60.0,1.073982,0.0,...,"[0.8902058080035272, 0.9205743151670118]",0.886390,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6295,6295,21,20,Cap,22.0,75.0,0.0,60.0,1.119203,0.0,...,"[0.9393122427677346, 1.2227954091560576]",1.092269,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6296,6296,21,21,Cap,22.0,75.0,0.0,60.0,1.096739,0.0,...,"[1.0013524343148736, 1.1412729625450908]",1.143522,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6319,6319,21,22,Cap,22.0,75.0,0.0,60.0,0.983302,0.0,...,"[0.7830258221537859, 0.9529324408806318]",1.072698,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6301,6301,21,23,Cap,22.0,75.0,0.0,60.0,1.064796,0.0,...,"[1.0215878272825876, 0.9464446124122178]",0.954916,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6308,6308,21,24,Cap,22.0,75.0,0.0,60.0,1.225095,0.0,...,"[0.9854571514562313, 0.859257647811257]",1.109772,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6307,6307,21,25,Cap,22.0,75.0,0.0,60.0,1.052353,0.0,...,"[0.9441795544672271, 1.066817793824832]",1.069565,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6310,6310,21,26,Cap,22.0,75.0,0.0,60.0,0.837732,0.0,...,"[0.8956910066778166, 1.121156529695747]",0.936593,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6302,6302,21,27,Cap,22.0,75.0,0.0,60.0,0.965815,0.0,...,"[1.0933180548412256, 0.9694325556116011]",1.137098,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6298,6298,21,28,Cap,22.0,75.0,0.0,60.0,0.937154,0.0,...,"[0.9676701240290696, 1.0406774658716325]",0.902229,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6322,6322,21,29,Cap,22.0,75.0,0.0,60.0,0.909214,0.0,...,"[0.8995185653833682, 1.018933390993687]",0.892491,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6303,6303,21,30,Cap,22.0,75.0,0.0,60.0,1.007785,0.0,...,"[1.1109123823039315, 1.0503612413797172]",1.063318,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6325,6325,21,31,Cap,22.0,75.0,0.0,60.0,0.902658,0.0,...,"[0.9462344713403261, 0.7435513636555972]",1.044157,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6288,6288,21,32,Cap,22.0,75.0,0.0,60.0,1.072283,0.0,...,"[1.0061185924375111, 0.944352139687777]",0.987034,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6327,6327,21,33,Cap,22.0,75.0,0.0,60.0,0.898880,0.0,...,"[1.0430288555965963, 1.1853959279932047]",1.067659,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6285,6285,21,34,Cap,22.0,75.0,0.0,60.0,1.106765,0.0,...,"[1.036432838202353, 0.859804959205568]",0.923572,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6313,6313,21,35,Cap,22.0,75.0,0.0,60.0,1.130658,0.0,...,"[1.1120947551596023, 0.9110775038358645]",1.029946,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6291,6291,21,36,Cap,22.0,75.0,0.0,60.0,1.104325,0.0,...,"[1.02102393754749, 1.0091744006745327]",0.986319,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6315,6315,21,37,Cap,22.0,75.0,0.0,60.0,1.149781,0.0,...,"[0.8867618960863003, 0.985170794135518]",1.095765,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6323,6323,21,38,Cap,22.0,75.0,0.0,60.0,0.963264,0.0,...,"[0.9435201450660196, 1.2509189321330192]",1.042676,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6309,6309,21,39,Cap,22.0,75.0,0.0,60.0,1.023547,0.0,...,"[1.1364815710763803, 0.9617278091015398]",0.873797,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6297,6297,21,40,Cap,22.0,75.0,0.0,60.0,0.730008,0.0,...,"[0.8947712434502784, 1.0508280292630074]",1.067508,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6314,6314,21,41,Cap,22.0,75.0,0.0,60.0,0.916972,0.0,...,"[0.9895325838999549, 1.0587236603849113]",1.009710,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6305,6305,21,42,Cap,22.0,75.0,0.0,60.0,0.886934,0.0,...,"[1.004655700711938, 1.1238652633536819]",1.063571,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6299,6299,21,43,Cap,22.0,75.0,0.0,60.0,0.984489,0.0,...,"[1.0008023173280796, 1.0894834066327972]",1.011055,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6289,6289,21,44,Cap,22.0,75.0,0.0,60.0,0.977594,0.0,...,"[1.0805226291654966, 1.0207855148383689]",0.875908,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6318,6318,21,45,Cap,22.0,75.0,0.0,60.0,0.934289,0.0,...,"[0.9032936024210803, 1.0091852134927595]",0.971557,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6283,6283,21,46,Cap,22.0,75.0,0.0,60.0,0.734553,0.0,...,"[0.9298952934309742, 0.8141235431867092]",0.999354,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6306,6306,21,47,Cap,22.0,75.0,0.0,60.0,0.998051,0.0,...,"[1.018097333113751, 1.0741439583438428]",1.150158,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6279,6279,21,48,Cap,22.0,75.0,0.0,60.0,1.033053,0.0,...,"[0.9560069034072676, 0.9330205530626483]",1.024739,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6316,6316,21,49,Cap,22.0,75.0,0.0,60.0,1.236445,0.0,...,"[0.828625666641839, 1.066328870028626]",1.242618,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0
6312,6312,21,50,Cap,22.0,75.0,0.0,60.0,0.993024,0.0,...,"[0.8278341043266377, 0.929188940537226]",1.088348,0.0,0.0,"[1.0, 1.0, 1.0]",[],0.0,0.0,1,0.0

In [54]:
firms_attribute_in.loc[firms_attribute_in['Type'] == 'Cap']

,AgentID,Type,Step,Size,Subsidiary,Quantity_ordered,Lifecycle,Inventories,Net_worth,Price,Wage,Productivity,Debt,Profits,Market_share,Capital_info
0,1,Cap,0,0,0,0,1,0,75,1.055371,1.051122,"[0.8666899625265944, 0.940817316002056]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
1,2,Cap,0,0,0,0,1,0,75,0.854037,1.090253,"[1.055513494940234, 1.026423713942426]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
2,3,Cap,0,0,0,0,1,0,75,0.870541,0.831982,"[1.0418818948631718, 0.8717691106970736]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
3,4,Cap,0,0,0,0,1,0,75,0.849033,1.060673,"[1.0239978916313308, 1.0417438246398965]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
4,5,Cap,0,0,0,0,1,0,75,1.157187,1.206313,"[1.2455125191371317, 0.9467347968677828]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
5,6,Cap,0,0,0,0,1,0,75,0.902430,1.056722,"[0.9303108649286114, 1.0073174777351475]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
6,7,Cap,0,0,0,0,1,0,75,1.048070,1.092050,"[0.9172334368146344, 0.9112498070059789]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
7,8,Cap,0,0,0,0,1,0,75,1.062561,0.913691,"[1.1491668762711038, 1.0827525759565915]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
8,9,Cap,0,0,0,0,1,0,75,1.072235,0.954718,"[0.9779819354742163, 1.144086930611596]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
9,10,Cap,0,0,0,0,1,0,75,1.091033,1.049766,"[0.88488912563192, 0.9111662887331813]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
10,11,Cap,0,0,0,0,1,0,75,1.005247,0.967572,"[1.0629693768179227, 0.9098426929839939]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
11,12,Cap,0,0,0,0,1,0,75,0.859988,1.166728,"[1.1124244220178618, 0.935642535431173]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
12,13,Cap,0,0,0,0,1,0,75,0.983566,0.891174,"[0.8596364669116047, 0.7938252285457353]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
13,14,Cap,0,0,0,0,1,0,75,0.933058,1.057868,"[0.9800196451730551, 0.9374351149644203]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
14,15,Cap,0,0,0,0,1,0,75,1.071198,0.953833,"[1.2141776173303902, 1.2471694408063372]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
15,16,Cap,0,0,0,0,1,0,75,1.085532,0.760227,"[1.1101198449029666, 1.133121946131287]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
16,17,Cap,0,0,0,0,1,0,75,1.017646,0.973425,"[0.9493744166559724, 0.8646471391501303]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
17,18,Cap,0,0,0,0,1,0,75,1.106909,1.223734,"[0.8733000939736986, 1.1094204802795855]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
18,19,Cap,0,0,0,0,1,0,75,1.050657,1.048495,"[0.9410289308067072, 1.0362072784549794]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
19,20,Cap,0,0,0,0,1,0,75,1.071354,1.006066,"[1.196694357388623, 0.8381543615192728]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
20,21,Cap,0,0,0,0,1,0,75,1.067156,1.117621,"[1.1009350865328376, 0.9778022485441246]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
21,22,Cap,0,0,0,0,1,0,75,1.104882,0.927082,"[0.9922878157023423, 1.1462018796594766]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
22,23,Cap,0,0,0,0,1,0,75,0.996279,1.207719,"[0.8888940938691311, 0.9341637052186259]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
23,24,Cap,0,0,0,0,1,0,75,1.005570,1.106010,"[0.9608335023337334, 1.0545227814709557]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
24,25,Cap,0,0,0,0,1,0,75,1.192079,0.911200,"[0.9104199675465613, 1.192757347202544]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
25,26,Cap,0,0,0,0,1,0,75,1.107181,0.901276,"[1.097043226371326, 1.126011529696674]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
26,27,Cap,0,0,0,0,1,0,75,1.085765,1.068693,"[1.047011960402475, 0.8630552689066466]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
27,28,Cap,0,0,0,0,1,0,75,1.067824,0.853829,"[0.962413350642549, 0.9545131059828303]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
28,29,Cap,0,0,0,0,1,0,75,0.881676,0.973952,"[1.0005729514380977, 0.9989256956477979]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
29,30,Cap,0,0,0,0,1,0,75,0.907107,1.181730,"[1.1525204731168524, 1.1129419062165662]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
30,31,Cap,0,0,0,0,1,0,75,0.976545,0.980784,"[0.8445899340647188, 0.9455976334160062]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
31,32,Cap,0,0,0,0,1,0,75,0.901869,0.856134,"[1.049912844599587, 0.9526665688112698]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
32,33,Cap,0,0,0,0,1,0,75,1.127852,1.260755,"[1.071982039933373, 0.9394543330728435]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
33,34,Cap,0,0,0,0,1,0,75,1.111902,0.926353,"[1.106362330419741, 0.8319437935861113]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
34,35,Cap,0,0,0,0,1,0,75,1.106349,0.944407,"[1.0659219015962003, 1.2201324531498488]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
35,36,Cap,0,0,0,0,1,0,75,1.106492,0.931969,"[1.0943393134479678, 0.9814012524580923]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
36,37,Cap,0,0,0,0,1,0,75,1.131278,0.921127,"[0.9196024609802702, 1.1989614164444276]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
37,38,Cap,0,0,0,0,1,0,75,1.069477,1.134772,"[1.0681733826811148, 0.8379350518941369]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
38,39,Cap,0,0,0,0,1,0,75,1.171762,0.985260,"[0.8742160305506812, 1.147556167262897]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
39,40,Cap,0,0,0,0,1,0,75,1.037817,1.097541,"[1.0767324473597388, 1.0778514401095214]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
40,41,Cap,0,0,0,0,1,0,75,0.946594,1.058643,"[0.8864631003410192, 1.0105017846709987]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
41,42,Cap,0,0,0,0,1,0,75,1.020905,1.069760,"[1.051676849392142, 0.9485617473991969]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
42,43,Cap,0,0,0,0,1,0,75,1.084541,1.068076,"[0.941178975898396, 1.0784381556685212]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
43,44,Cap,0,0,0,0,1,0,75,1.143649,0.886102,"[0.8192882964554662, 1.0086318649759498]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
44,45,Cap,0,0,0,0,1,0,75,1.075952,0.989135,"[0.872826689211931, 1.0828270576794479]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
45,46,Cap,0,0,0,0,1,0,75,1.104501,1.038106,"[1.179866309394039, 1.1421288048276033]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
46,47,Cap,0,0,0,0,1,0,75,1.179439,1.022593,"[1.1956224311439032, 0.7761980245490898]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
47,48,Cap,0,0,0,0,1,0,75,0.960132,0.966630,"[1.1337077686319483, 0.9153817571510736]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
48,49,Cap,0,0,0,0,1,0,75,1.065852,0.992800,"[1.1387398336600147, 0.9759435234391456]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"
49,50,Cap,0,0,0,0,1,0,75,0.961084,1.009013,"[1.060395666201444, 0.986933169417024]",0,0,"[1, 1, 1]","[[0, 10, 1], [0, 10, 1], [0, 10, 1], [0, 10, 1]]"

In [10]:
households_attribute_out = pd.read_csv('CRAB/Inputs/micro_variable_hh_out_26850')

In [11]:
households_attribute_in = pd.read_csv('CRAB/Inputs/micro_variable_hh_in_26850')

In [12]:
len(households_attribute_in), len(households_attribute_out)

(1000, 22000)

In [13]:
households_attribute_out
# select only Step == 21
households_attribute_out = households_attribute_out.loc[households_attribute_out['Step'] == 21]
len(households_attribute_out)

1000

In [15]:
households_attribute_out.head(2)

,Unnamed: 0,Step,AgentID,Flood_prob,Worry,RE_elev,RE_wet,RE_dry,SE_elev,SE_wet,...,PC_wet,PC_dry,Flood_exp,Social_exp,Education,Lifecycle,t,Savings_norm,HH_sell_norm,OMEGA
21000,21000,21,301,0.02,1.0,3.0,3.0,3.000000,3.0,4.666667,...,3.333333,4.000000,0.0,4.0,3.0,21.0,1,0.590,26.100542,NaN
21001,21001,21,302,0.10,1.0,3.0,4.0,4.666667,4.0,3.333333,...,3.000000,2.666667,0.0,1.0,2.0,21.0,1,0.168,8.700181,NaN

In [14]:
households_attribute_in.head(2)

,Unnamed: 0,Step,AgentID,Flood_prob,Worry,RE_elev,RE_wet,RE_dry,SE_elev,SE_wet,...,Flood_exp,Social_exp,Education,Lifecycle,t,Savings_norm,HH_sell_norm,OMEGA,C,Y
0,21000,21,301,0.02,1.0,3.0,3.0,3.000000,3.0,4.666667,...,0.0,4.0,3.0,21.0,1,0.590,26.100542,NaN,12.265147,15.23935
1,21001,21,302,0.10,1.0,3.0,4.0,4.666667,4.0,3.333333,...,0.0,1.0,2.0,21.0,1,0.168,8.700181,NaN,12.265147,15.23935

In [55]:
households_init = pd.read_csv("CRAB/Inputs/HH_attributes_us")

In [59]:
households_init =  households_init.sample(1000).reset_index(drop=True)
        # add in socio_economic_hh_attributes the variable 'AgentID'
#socio_economic_hh_attributes['AgentID'] = socio_economic_hh_attributes.index + F1 + F2+ F3 + 1

In [60]:
households_init

,Unnamed: 0,Flood_prob,Worry,RE_elev,RE_wet,RE_dry,SE_elev,SE_wet,SE_dry,PC_elev,...,Education,Savings_norm,HH_sell_norm,t,OMEGA,CPC,Y,I,C,AgentID
0,2117,0.20,4.0,1.0,1.000000,1.000000,1.0,1.000000,1.000000,5.0,...,4.0,3.444,203.004218,2,NaN,39.249089,NaN,3.158033,NaN,2679
1,4177,0.50,3.0,5.0,5.000000,5.000000,5.0,1.000000,1.000000,5.0,...,2.0,0.275,17.400362,2,NaN,39.249089,NaN,3.158033,NaN,4739
2,367,0.50,3.0,2.0,3.333333,3.333333,1.0,1.000000,1.000000,5.0,...,3.0,0.000,52.201085,2,NaN,39.249089,NaN,3.158033,NaN,929
3,2316,0.50,3.0,4.0,2.666667,2.000000,1.0,3.333333,5.000000,5.0,...,4.0,2.270,29.000603,2,NaN,39.249089,NaN,3.158033,NaN,2878
4,4554,0.50,2.0,2.0,1.666667,2.000000,1.0,2.333333,2.000000,5.0,...,2.0,2.563,20.300422,2,NaN,39.249089,NaN,3.158033,NaN,5116
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,4900,0.20,2.0,3.0,3.000000,2.666667,2.0,2.666667,3.000000,3.0,...,4.0,3.138,26.100542,2,NaN,39.249089,NaN,3.158033,NaN,5462
996,1015,0.40,3.0,3.0,1.666667,1.000000,1.0,1.000000,1.000000,3.0,...,2.0,0.134,10.150211,2,NaN,39.249089,NaN,3.158033,NaN,1577
997,1695,1.00,5.0,5.0,5.000000,5.000000,5.0,4.000000,5.000000,5.0,...,4.0,0.494,11.600241,2,NaN,39.249089,NaN,3.158033,NaN,2257
998,47,0.10,2.0,3.0,3.000000,3.000000,3.0,3.000000,3.000000,3.0,...,3.0,0.000,4.000000,2,NaN,39.249089,NaN,3.158033,NaN,609
999,853,0.05,1.0,3.0,3.000000,3.000000,4.0,3.333333,2.666667,3.0,...,3.0,0.721,8.700181,2,NaN,39.249089,NaN,3.158033,NaN,1415

In [15]:
max_step =households_attribute_in['Step'].max()
socio_economic_hh_attributes = households_attribute_in.loc[households_attribute_in['Step'] == max_step]

In [16]:
socio_economic_hh_attributes

,Unnamed: 0,Step,AgentID,Flood_prob,Worry,RE_elev,RE_wet,RE_dry,SE_elev,SE_wet,...,Flood_exp,Social_exp,Education,Lifecycle,t,Savings_norm,HH_sell_norm,OMEGA,C,Y
0,21000,21,301,0.00,1.0,1.0,1.000000,1.000000,5.0,5.000000,...,0.0,1.0,3.0,21.0,0,2.106,14.500301,NaN,NaN,NaN
1,21001,21,302,0.25,2.0,5.0,4.333333,4.000000,5.0,4.333333,...,0.0,5.0,3.0,21.0,0,1.111,15.370319,NaN,NaN,NaN
2,21002,21,303,0.20,3.0,4.0,4.000000,4.000000,3.0,3.000000,...,0.0,3.0,2.0,21.0,0,0.095,20.300422,NaN,NaN,NaN
3,21003,21,304,0.95,1.0,4.0,2.666667,1.666667,1.0,2.000000,...,0.0,4.0,4.0,21.0,0,0.375,15.660325,NaN,NaN,NaN
4,21004,21,305,0.00,1.0,3.0,3.000000,3.000000,1.0,1.000000,...,0.0,1.0,2.0,21.0,0,0.709,22.330464,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,21995,21,1296,0.25,3.0,5.0,5.000000,5.000000,1.0,1.000000,...,1.0,3.0,3.0,21.0,0,0.612,30.740639,NaN,NaN,NaN
996,21996,21,1297,0.50,3.0,3.0,4.666667,5.000000,1.0,1.000000,...,0.0,1.0,2.0,21.0,0,0.000,6.960145,NaN,NaN,NaN
997,21997,21,1298,0.00,3.0,2.0,2.333333,3.000000,2.0,2.666667,...,0.0,4.0,2.0,21.0,0,0.000,16.530343,NaN,NaN,NaN
998,21998,21,1299,0.01,2.0,3.0,3.000000,3.000000,3.0,3.000000,...,0.0,3.0,2.0,21.0,0,1.184,34.800723,NaN,NaN,NaN
999,21999,21,1300,0.05,2.0,3.0,3.000000,3.000000,1.0,1.000000,...,0.0,1.0,4.0,21.0,0,0.304,14.500301,NaN,NaN,NaN

In [10]:
households_attribute_in.head(2)

,Unnamed: 0,Step,AgentID,Flood_prob,Worry,RE_elev,RE_wet,RE_dry,SE_elev,SE_wet,...,Flood_exp,Social_exp,Education,Lifecycle,t,Savings_norm,HH_sell_norm,OMEGA,C,Y
0,21000,21,301,0.00,1.0,1.0,1.000000,1.0,5.0,5.000000,...,0.0,1.0,3.0,21.0,0,2.106,14.500301,NaN,NaN,NaN
1,21001,21,302,0.25,2.0,5.0,4.333333,4.0,5.0,4.333333,...,0.0,5.0,3.0,21.0,0,1.111,15.370319,NaN,NaN,NaN

In [9]:
households_attribute_out.head(2)

,Unnamed: 0,Step,AgentID,Flood_prob,Worry,RE_elev,RE_wet,RE_dry,SE_elev,SE_wet,...,PC_wet,PC_dry,Flood_exp,Social_exp,Education,Lifecycle,t,Savings_norm,HH_sell_norm,OMEGA
0,0,0,301,0.00,1.0,1.0,1.000000,1.0,5.0,5.000000,...,5.000000,5.0,0.0,1.0,3.0,0.0,1,2.106,14.500301,NaN
1,1,0,302,0.25,2.0,5.0,4.333333,4.0,5.0,4.333333,...,4.333333,4.0,0.0,5.0,3.0,0.0,1,1.111,15.370319,NaN

In [ ]:
# is there the value 1253 in the AgentID column of households_attribute_in?
households_attribute_in[households_attribute_in['AgentID'] == 1253]

In [ ]:
import networkx as nx

In [ ]:
G = nx.read_graphml('CRAB/Inputs/crab_network_26850.graphml')

In [ ]:
G
# what is the number of nodes in G
len(G.nodes()) 
# does G have a node 924?
G.has_node('924')

In [ ]:
G.neighbors(125)

In [ ]:
firms_attribute_in

In [ ]:
firms_attribute_out = pd.read_csv('CRAB/Inputs/micro_variable_firms_out_26850')

In [ ]:
firms_attribute_out.head(1)

In [ ]:
hh_out.head(1)

In [ ]:
micro_data = pd.read_csv('IT_PUF_EUSILC/IT_2013p_EUSILC.csv')

In [ ]:
micro_data